apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-http-client
  namespace: app-dev
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: go-http-client
  template: ## Pod
    metadata:
      labels:
        app: go-http-client
    spec:
      containers:
      - name: client
        image: kixualx/http-client:0.0.1
        command: ["./app"]
        #args: ["-url", "http://10.42.0.202:8080", "-interval", "3"]
        ##args: ["-url", "http://server-svc.app-dev.svc.cluster.local:8080", "-interval", "3"]
        args: ["-url", "http://server-svc:8080/cakes", "-interval", "3"]
#Узнать домен можно командой kubectl run -it --image=ubuntu --restart=Never shell -- \
#sh -c 'apt-get update > /dev/null && apt-get install -y dnsutils > /dev/null && \
#nslookup kubernetes.default | grep Name | sed "s/Name:\skubernetes.default//"'

