apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
  namespace: home-dev
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 100
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the K8S cluster
          restartPolicy: Never
