apiVersion: v1
kind: Namespace 
metadata:
  name: ds-test

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: http-server-daemonset
  namespace: ds-test
  labels:
    app: http-server
spec:
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
      - name: server
        image: kixualx/http-server:0.0.1
        ports:
        - containerPort: 8080
          name: web
