apiVersion: v1
kind: Namespace
metadata:
  name: read-cm

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-file-reader
  namespace: read-cm
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: go-file-reader
  template:
    metadata:
      labels:
        app: go-file-reader
    spec:
      containers:
      - name: reader
        image: kixualx/file-reader:0.0.3
        command: ["./app"]
        args: ["-p", "/."]
        volumeMounts:
        - name: config-volume
          mountPath: /some.json
          subPath: some.json
        - name: config-volume2
          mountPath: /some2.json
          subPath: some2.json
      volumes:
      - name: config-volume
        configMap:
          name: some-cm
      - name: config-volume2
        configMap:
          name: some-cm2
