apiVersion: v1
kind: Service
metadata:
  namespace: app-stage
  name: server-svc
spec:
  type: NodePort
  selector:
    app: go-http-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort:  8080
      nodePort: 30080 #30000-30767
