apiVersion: v1
kind: Namespace
metadata:
  name: probes-test

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-http-server
  namespace: probes-test
spec:
  strategy: 
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: go-http-server
  template:
    metadata:
      labels:
        app: go-http-server
    spec:
      containers:
      - name: server
        image: kixualx/http-server:0.0.2
        ports:
        - containerPort: 8080
          name: web

---

apiVersion: v1
kind: Service
metadata:
  namespace: probes-test
  name: http-server
spec:
  selector:
    app: go-http-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
